server:
  port: 9999


#数据源配置         useUnicode=true&charsetEncoding=utf-8
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
  #热部署
  devtools:
    restart:
      enabled: true
      #设置重启的目录,添加目录的文件需要restart
      additional-paths: src/main/java
      #解决项目重启后报404的问题
      poll-interval: 3000
      quiet-period: 1000
  #ehcache  Ehcache(5)配置yml
  cache:
    ehcache:
      config: classpath:ehcache.xml

#mybatis配置
mybatis:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.xxx.springboot.vo
  configuration:
    map-underscore-to-camel-case: true

#分页
pagehelper:
  auto-dialect: mysql

#日志
logging:
  level:
    com:
      xxx:
        springboot:
          dao: debug


